importReactUseStateFromReact
importUseFormikFromFormik
importAxiosFromAxios
importValidationSchemaFromUtils
importAdapterDayjsFromMuiXDatePickersAdapterDayjs
importLocalizationProviderFromMuiXDatePickersLocalizationProvider
importDatePickerFromMuiXDatePickersDatePicker
import
textField
radio
checkbox
formLabel
formControlLabel
radioGroup
formControl
button
snackbar
tab
menuItem
select
card
fromMuiMaterial
importDeliveryFormScss
import
counterParties
unitList
complienceList
feedBackStockList
tabList
compliantList
batchType
baseApiUrl
fromConstants
importMuiAlertFromMuiMaterialAlert
importTabContextTabPanelFromMuiLab

constAlertReactForwardRefFunctionAlertPropsRef
returnMuiAlertElevation_6RefRefVariantFilledProps


constDeliveryForm
constOpenAlertSetOpenAlertUseStateFalse
constFileNameSetFilenameUseState
constSelectedFileSetSelectedFileUseState

constInitialBatchDetailsQuantityOrigin
constBatchDetailsSetBatchDetailsUseStateInitialBatchDetails

constInitialMillBatchDetails
millName
certNum
estateName
certNumCover
isEpa
isEu
wareHouseName
certNumWareHouse
wareHouseLoc
loadedQuantity
batchNo
totalGhgEMission

constMillBatchDetailsSetMillBatchDetailsUseState
initialMillBatchDetails


constInitialRefineryDetails
refinaryName
certNumOfRefinery
refineryLoc
warePriorshipment
wareCertNum
warehousecity
loadedQuant
batchNoTwo

constRefineryDetailsSetRefineryDetailsUseState
initialRefineryDetails


constInitialShippedVolumeDetails
estateNamelast
prodFrom
prodTo
febSupplied
cpoProduced

constShippedVolumeDetailsSetShippedVolumeDetailsUseState
initialShippedVolumeDetails


constTabIndexSetTabindexUseState_0
constSuccessSetSuccessUseStateSuccess
constMsgSetMsgUseState

constFormikUseFormik
initialValues
sellerCompanyName
sellerCompAddress
contactPersonName
contectPersonTel
buyerRef
sellerRef
certSysName
certNumberOfSeller
nameOfCertBody
certIssueDate
vesselName
blDate
uniqDelNum
loadingPort
dischargePort
avgMonthVolume
recipientAdd
loadedQuantity
feedBackStockType
file
compliences
batchDetails
millBatchDetails
refineryDetails
shippedVolumeDetails

validationSchemaValidationSchema
onSubmitValues
debugger
consoleLogSelectedFile
consoleLogBatchDetails
consoleLogRefineryDetails
consoleLogMillBatchDetails
consoleLogShippedVolumeDetails
constNewSelectedFileSelectedFile
constFilesSelectedFileSelectedFile
constDataNewFormData
filesForEachFileI
dataAppendFileIFileFileName

valuesFileFiles
valuesBatchDetailsBatchDetails
valuesMillBatchDetailsMillBatchDetails
valuesRefineryDetailsRefineryDetails
valuesShippedVolumeDetailsShippedVolumeDetails
consoleLogValues
submitDeliveryFormValues




updateEachFiledInLoopGenericFunction
paramEve
paramDataList
paramIndex
paramKeyName
paramType

constUpdateFieldValEveDataListIndexKeyNameType
debugger
constUpdatedListDataListIndexKeyNameEveTargetValue
constNewList
dataListSlice_0Index
updatedList
dataListSliceIndex_1

ifTypeBatchTypeSeller
setBatchDetailsNewList

ifTypeBatchTypeEstatemill
setMillBatchDetailsNewList

ifTypeBatchTypeRefinerywarehousedata
setRefineryDetailsNewList

ifTypeBatchTypeShippedproducedvol
setShippedVolumeDetailsNewList




formSunmissionMethod
paramFormValues

constSubmitDeliveryFormFormValues
constFilesSelectedFileSelectedFile
constDataNewFormData
filesForEachFileI
dataAppendFileIFileFileName

constRequestOptions
methodPost
headersContentTypeApplicationJson
modeNoCors
bodyData

fetchBaseApiUrlCreateSupplierCriteriaInputRequestOptions
thenAsyncResponse
formikResetForm
setOpenAlertOpenAlert
setSuccessSuccess
setMsgDataSuccessfullySubmitted

catchError
setOpenAlertOpenAlert
formikResetForm
setSuccessError
setMsgSomeErrorOccured


axios
postBaseApiUrlGetSupplierCriteriaInputFormValues
headers
contentTypeMultipartFormData

thenRes
consoleLogRes
formikResetForm
setOpenAlertOpenAlert
setSuccessSuccess
setMsgDataSuccessfullySubmitted
setBatchDetailsInitialBatchDetails
setMillBatchDetailsInitialMillBatchDetails
setRefineryDetailsInitialRefineryDetails
setShippedVolumeDetailsInitialShippedVolumeDetails

catchErr
setOpenAlertOpenAlert
formikResetForm
setSuccessError
setMsgSomeErrorOccured
consoleErrorThereWasAnErrorErr
setBatchDetailsInitialBatchDetails
setMillBatchDetailsInitialMillBatchDetails
setRefineryDetailsInitialRefineryDetails
setShippedVolumeDetailsInitialShippedVolumeDetails





addNewRowUniversalFunction
paramBatchDetails
paramLimit

constAddNewRowDataListLimitType
ifDataListLengthLimit
ifTypeBatchTypeSeller
setBatchDetailsOldArrayOldArrayInitialBatchDetails

ifTypeBatchTypeEstatemill
setMillBatchDetailsOldArray
oldArray
initialMillBatchDetails


ifTypeBatchTypeRefinerywarehousedata
setRefineryDetailsOldArrayOldArrayInitialRefineryDetails

ifTypeBatchTypeShippedproducedvol
setShippedVolumeDetailsOldArray
oldArray
initialShippedVolumeDetails






removeFieldsFromALoop

paramDelindex
paramDatalist
paramType
returns

constRemoveRowDelindexDatalistType
ifDatalistLength_2
return

ifTypeBatchTypeSeller
setBatchDetailsBatchs
batchsFilterIndexIndexDelindex


ifTypeBatchTypeEstatemill
setMillBatchDetailsBatchs
batchsFilterIndexIndexDelindex


ifTypeBatchTypeRefinerywarehousedata
setRefineryDetailsBatchs
batchsFilterIndexIndexDelindex


ifTypeBatchTypeShippedproducedvol
setShippedVolumeDetailsBatchs
batchsFilterIndexIndexDelindex




return

tabContextValueTabIndex
formOnSubmitFormikHandleSubmit
divClassNameTabWrapper
tabListMapTabDataIndex
return
tab
labelTabDataLabel
valueIndexToString
classNameIndexToStringTabIndexActiveTab
onClick
setTabindexIndexToString
consoleLogFormikValuesBatchDetails
formikSetFieldValueBatchDetailsBatchDetails




div

sellerCargoDetailsTabContentStart
tabPanelValue_0
snackbar
anchorOriginVerticalTopHorizontalRight
openOpenAlert
autoHideDuration_3000
onCloseSetOpenAlertOpenAlert

alert
onCloseSetOpenAlertFalse
severitySuccess
sxWidth_100

msg
alert
snackbar
divClassNameDeliveryFormWrapper
h3SellerAndCargoDetailsH3
divClassNameFormWrapper
h4
a1SellerDetailsPleaseProvideHereYourOwnDetails
h4
formControlClassNameInputWrapper
textField
fullWidth
idSellerCompanyName
nameSellerCompanyName
variantStandard
keySellerCompanyName
labelSellerCompanyName
valueFormikValuesSellerCompanyName
onChangeFormikHandleChange
onBlurFormikHandleBlur
autoCompleteOff
error
formikTouchedSellerCompanyName
booleanFormikErrorsSellerCompanyName

helperText
formikTouchedSellerCompanyName
formikErrorsSellerCompanyName


formControl

formControlClassNameInputWrapper
textField
fullWidth
idSellerCompAddress
variantStandard
nameSellerCompAddress
labelSellerCompanyAddress
valueFormikValuesSellerCompAddress
onChangeFormikHandleChange
autoCompleteOff
onBlurFormikHandleBlur
error
formikTouchedSellerCompAddress
booleanFormikErrorsSellerCompAddress

helperText
formikTouchedSellerCompAddress
formikErrorsSellerCompAddress


formControl

formControlClassNameInputWrapper
textField
fullWidth
idContactPersonName
variantStandard
nameContactPersonName
labelContactPersonName
valueFormikValuesContactPersonName
onChangeFormikHandleChange
autoCompleteOff

formControl

formControlClassNameInputWrapper
textField
fullWidth
idContectPersonTel
variantStandard
nameContectPersonTel
labelContactPersonTelephone
valueFormikValuesContectPersonTel
onChangeFormikHandleChange
autoCompleteOff

formControl

h4ContractReferenceNumberH4
formControlClassNameInputWrapper
textField
fullWidth
variantStandard
idBuyerRef
nameBuyerRef
labelBuyerReference
valueFormikValuesBuyerRef
onChangeFormikHandleChange
autoCompleteOff

formControl

formControlClassNameInputWrapper
textField
fullWidth
idSellerRef
variantStandard
nameSellerRef
labelSellerReference
valueFormikValuesSellerRef
onChangeFormikHandleChange
autoCompleteOff

formControl

h4A2SellerSCertificateDetailsH4

formControlClassNameInputWrapper
textField
fullWidth
idCertSysName
variantStandard
nameCertSysName
labelNameOfTheCertificationSystem
valueFormikValuesCertSysName
onChangeFormikHandleChange
autoCompleteOff

formControl

formControlClassNameInputWrapper
textField
fullWidth
idCertNumberOfSeller
variantStandard
nameCertNumberOfSeller
labelCertificateNumberOfTheSeller
valueFormikValuesCertNumberOfSeller
onChangeFormikHandleChange
autoCompleteOff

formControl

formControlClassNameInputWrapper
textField
width_50
idNameOfCertBody
nameNameOfCertBody
variantStandard
labelNameOfTheCertificationBody
valueFormikValuesNameOfCertBody
onChangeFormikHandleChange
autoCompleteOff

formControl

formControlClassNameInputWrapperDateWrapper
localizationProviderDateAdapterAdapterDayjs
datePicker
sizeLarge
labelBLDateDdMmYyyy
formatDdMmYyyy
valueFormikValuesCertIssueDate
onChangeValue
formikSetFieldValueCertIssueDateValueTrue

slotProps
textField
variantStandard
errorFalse



localizationProvider
formControl

h4B2LoadedQuantityUnitMeasureAndFeedstockTypeH4

formControlClassNameInputWrapper
textField
fullWidth
idVesselName
nameVesselName
variantStandard
labelVesselBargeName
valueFormikValuesVesselName
onChangeFormikHandleChange
autoCompleteOff

formControl

formControlClassNameInputWrapperDateWrapper
localizationProviderDateAdapterAdapterDayjs
datePicker
sizeLarge
labelBLDateDdMmYyyy
formatDdMmYyyy
valueFormikValuesBlDate
onChangeValue
formikSetFieldValueBlDateValueTrue

slotProps
textField
variantStandard
errorFalse



localizationProvider
formControl

formControlClassNameInputWrapper
textField
fullWidth
idUniqDelNum
nameUniqDelNum
variantStandard
labelAUniqueDeliveryNumber
valueFormikValuesUniqDelNum
onChangeFormikHandleChange
autoCompleteOff

formControl
formControlClassNameInputWrapper
textField
fullWidth
idLoadingPort
nameLoadingPort
variantStandard
labelLoadingPort
valueFormikValuesLoadingPort
onChangeFormikHandleChange
autoCompleteOff

formControl
formControlClassNameInputWrapper
textField
fullWidth
idDischargePort
nameDischargePort
variantStandard
labelDischargePort
valueFormikValuesDischargePort
onChangeFormikHandleChange
autoCompleteOff

formControl

formControlComponentFieldsetClassNameInputWrapper
formLabelComponentLegendClassNameFormLabel
nameAndAddressOfRecipientNesteCounterparty
formLabel
radioGroup
ariaLabelRecipientAdd
nameRecipientAdd
valueFormikValuesRecipientAdd

counterPartiesMapOptionIndx
formControlLabel
keyOptionValueIndx
valueOptionValue
onChangeFormikHandleChange
controlRadioColorDefault
labelOptionLabel
defaultCheckedFormikValuesRecipientAdd


radioGroup
formControl

formControlClassNameCustomInputWrapper
textField
fullWidth
idLoadedQuantity
nameLoadedQuantity
variantStandard
labelLoadedQuantity
valueFormikValuesLoadedQuantity
onChangeFormikHandleChange
autoCompleteOff

divClassNameMonthVol
radioGroup
ariaLabelAvgMonthVolume
nameAvgMonthVolume
valueFormikValuesAvgMonthVolume

unitListMapOptionIndx
formControlLabel
keyOptionValueIndx
valueOptionValue
onChangeFormikHandleChange
controlRadioColorDefault
labelOptionLabel
defaultCheckedFormikValuesGender


radioGroup
div
formControl

formControlComponentFieldsetClassNameInputWrapper
formLabelComponentLegendClassNameFormLabel
feedstockType
formLabel
feedBackStockListMapFeedBackStockTypeOptionIndx
formControlLabel
keyFeedBackStockTypeOptionValueIndx
nameFeedBackStockType
control
checkbox
colorDefault
checkedFormikValuesFeedBackStockTypeIncludes
feedBackStockTypeOptionValue

valueFeedBackStockTypeOptionValue
onChangeEv
ifEvTargetChecked
formikValuesFeedBackStockTypePush
evTargetValue

else
constIndex
formikValuesFeedBackStockTypeIndexOf
evTargetValue

ifIndex_1
formikValuesFeedBackStockTypeSplice
index
1



formikValidateForm

nameFeedBackStockTypeOptionValue


labelFeedBackStockTypeOptionLabel


formControl

formControlClassNameUploadButtonWrapper
formLabelComponentLegendClassNameFormLabel
uploadCerirficate
formLabel
buttonVariantContainedComponentLabel
upload
input
idFile
nameFile
multipleTrue
hidden
typeFile
onChangeEvent
setSelectedFileEventTargetFiles
setFilename
eventTargetFilesLength_1
eventTargetFilesLengthFilesSelected
eventCurrentTargetFiles_0Name



button
fileName
formControl
brBr
h4B3MarketComplianceInformationH4
formControlComponentFieldsetClassNameInputWrapper
formLabelComponentLegendClassNameFormLabel
complianceType
formLabel
complienceListMapComplienceOption
formControlLabel
keyComplienceOptionValue
nameCompliences
control
checkbox
colorDefault
checkedFormikValuesCompliencesIncludes
complienceOptionValue

valueComplienceOptionValue
onChangeEv
ifEvTargetChecked
formikValuesCompliencesPushEvTargetValue
else
constIndexFormikValuesCompliencesIndexOf
evTargetValue

ifIndex_1
formikValuesCompliencesSpliceIndex_1


formikValidateForm

nameComplienceOptionValue


labelComplienceOptionLabel


formControl

batchDetailsMapBatchIndex
return

divClassNameCustomInputWrapper
formLabelComponentLabelClassNameBatchFormlabel
batchIndex_1
formLabel
textField
fullWidth
idBatchQuantity
nameBatch
variantStandard
labelLoadedQuantityMt
valueBatchDetailsIndexQuantity
onChangeEvent
updateFieldVal
event
batchDetails
index
quantity
batchTypeSeller


autoCompleteOff

textField
fullWidth
idBatchOrigin
nameBatchOrigin
variantStandard
labelOrigin
valueBatchDetailsIndexOrigin
onChangeEvent
updateFieldVal
event
batchDetails
index
origin
batchTypeSeller


autoCompleteOff


p
titleRemove
className
batchDetailsLength_2
removeNotAllowed
remove

onClick
removeRowIndexBatchDetailsBatchTypeSeller



p
div



p
classNameAdd
titleAddNewBatch
onClickAddNewRowBatchDetails_7BatchTypeSeller


p
div
div
tabPanel

sellerCargoDetailsTabContentEnd

traceabilityGhgDetailsTabContentStart

tabPanelValue_1
snackbar
anchorOriginVerticalTopHorizontalRight
openOpenAlert
autoHideDuration_3000
onCloseSetOpenAlertOpenAlert

alert
onCloseSetOpenAlertFalse
severitySuccess
sxWidth_100

msg
alert
snackbar
divClassNameTraceabilityGhgformWrapper
h3TraceabilityGhgInformationDetailsH3
divClassNameFormWrapper
h4D1EstateAndMillDataH4
millBatchDetailsMapMillbatchIndex
return

cardClassNameEachTranciabilityWrapper
divClassNameCustomInputWrapper
textField
fullWidth
idMillbatchMillName
nameMillName
variantStandard
labelMillName
valueMillbatchMillName
onChangeEvent
updateFieldVal
event
millBatchDetails
index
millName
batchTypeEstatemill


autoCompleteOff

textField
fullWidth
idMillbatchCertNum
nameMillbatchCertNum
variantStandard
labelCertificateNumberOfTheMill
valueMillbatchCertNum
onChangeEvent
updateFieldVal
event
millBatchDetails
index
certNum
batchTypeEstatemill


autoCompleteOff

textField
fullWidth
idMillbatchEstateName
nameEstateName
variantStandard
labelNameOfEstateSOrSmallholders
valueMillbatchEstateName
onChangeEvent
updateFieldVal
event
millBatchDetails
index
estateName
batchTypeEstatemill


autoCompleteOff

textField
fullWidth
idMillbatchCertNumCover
nameMillbatchCertNumCover
variantStandard
labelCertificateNumberCoveringTheSmallholdersIfApplicable
valueFormikValuesBatchDetailsCertNumCover
onChangeEvent
updateFieldVal
event
millBatchDetails
index
certNumCover
batchTypeEstatemill


autoCompleteOff

div

divClassNameCustomInputWrapper
formLabelComponentLabelClassNameOptionLabel
dec_19th_2007IfEpaCompliant
formLabel
select
classNameOptionEpa
labelIdIsEpa
variantStandard
idMillbatchIsEpa
nameMillbatchIsEpa
valueMillbatchIsEpa
onChangeEvent
updateFieldVal
event
millBatchDetails
index
isEpa
batchTypeEstatemill



compliantListMapOptionIndx
menuItem
keyOptionValueIndx
valueOptionValue

optionLabel
menuItem

select

formLabelComponentLabelClassNameOptionLabel
jan_1th_2008IfEuRedCompliant
formLabel
select
classNameOptionEpa
labelIdIsEu
variantStandard
idMillbatchIsEu
nameMillbatchIsEu
valueMillbatchIsEu
onChangeEvent
updateFieldVal
event
millBatchDetails
index
isEu
batchTypeEstatemill



compliantListMapOptionIndx
menuItem
keyOptionValueIndx
valueOptionValue

optionLabel
menuItem

select
div

divClassNameCustomInputWrapper
textField
keyIndexMillbatchOrigin
fullWidth
idFormikMillbatchDetails
nameMillbatchWareHouseName
variantStandard
labelNameOfTheWarehousePortPriorToShipment
valueFormikValuesBatchDetailsOrigin
onChangeEvent
updateFieldVal
event
millBatchDetails
index
wareHouseName
batchTypeEstatemill


autoCompleteOff

textField
fullWidth
idFormikCertNumWareHouse
nameFormikCertNumWareHouse
variantStandard
labelCertificateNumberOfTheWarehousePort
valueFormikValuesBatchDetailsOrigin
onChangeEvent
updateFieldVal
event
millBatchDetails
index
certNumWareHouse
batchTypeEstatemill


autoCompleteOff

textField
fullWidth
idMillbatchOrigin
nameMillbatchOrigin
variantStandard
labelLocationOfTheWarehouseCityCountry
valueFormikValuesBatchDetailsOrigin
onChangeEvent
updateFieldVal
event
millBatchDetails
index
wareHouseLoc
batchTypeEstatemill


autoCompleteOff

div

divClassNameCustomInputWrapper
textField
fullWidth
idMillbatchOrigin
nameMillbatchOrigin
variantStandard
labelLoadedQuantityMt
valueFormikValuesBatchDetailsOrigin
onChangeEvent
updateFieldVal
event
millBatchDetails
index
loadedQuantity
batchTypeEstatemill


autoCompleteOff

textField
fullWidth
idMillbatchOrigin
nameMillbatchOrigin
variantStandard
labelBatchNoFromSectionCTab_1
valueFormikValuesBatchDetailsOrigin
onChangeEvent
updateFieldVal
event
millBatchDetails
index
batchNo
batchTypeEstatemill


autoCompleteOff

textField
fullWidth
idMillbatchOrigin
nameMillbatchOrigin
variantStandard
labelTotalGhgEmissionFromTheSupplyAndUseOfTheFuel
valueFormikValuesBatchDetailsOrigin
onChangeEvent
updateFieldVal
event
millBatchDetails
index
totalGhgEMission
batchTypeEstatemill


autoCompleteOff

p
titleRemove
className
millBatchDetailsLength_2
removeNotAllowed
remove

onClick
removeRow
index
millBatchDetails
batchTypeEstatemill




p
div
card



p
classNameAdd
titleAddNewBatch
onClick
addNewRow
millBatchDetails
batchDetailsLength
batchTypeEstatemill




p
div

divClassNameFormWrapper
h4D2RefineryAndWarehouseDataH4
refineryDetailsMapRefinerybatchIndex
return

cardClassNameEachTranciabilityWrapper
divClassNameCustomInputWrapper
textField
fullWidth
idRefinerybatchRefinaryName
nameRefinaryName
variantStandard
labelNameOfTheRefinery
valueRefinerybatchRefinaryName
onChangeEvent
updateFieldVal
event
refineryDetails
index
refinaryName
batchTypeRefinerywarehousedata


autoCompleteOff

textField
fullWidth
idRefinerybatchCertNumOfRefinery
nameRefinerybatchCertNumOfRefinery
variantStandard
labelCertificateNumberOfTheRefinery
valueRefinerybatchCertNumOfRefinery
onChangeEvent
updateFieldVal
event
refineryDetails
index
certNumOfRefinery
batchTypeRefinerywarehousedata


autoCompleteOff

textField
fullWidth
idRefinerybatchRefineryLoc
nameRefineryLoc
variantStandard
labelLocationOfTheRefinery
cityCountry
valueRefinerybatchRefineryLoc
onChangeEvent
updateFieldVal
event
refineryDetails
index
refineryLoc
batchTypeRefinerywarehousedata


autoCompleteOff

textField
fullWidth
idRefinerybatchWarePriorshipment
nameRefinerybatchWarePriorshipment
variantStandard
labelNameOfTheWarehousePortPriorToShipment
valueRefinerybatchWarePriorshipment
onChangeEvent
updateFieldVal
event
refineryDetails
index
warePriorshipment
batchTypeRefinerywarehousedata


autoCompleteOff

div

divClassNameCustomInputWrapper
textField
fullWidth
idRefinerybatchWareCertNum
nameRefinerybatchWareCertNum
variantStandard
labelCertificateNumberOfTheWarehousePort
valueRefinerybatchOrigin
onChangeEvent
updateFieldVal
event
refineryDetails
index
wareCertNum
batchTypeRefinerywarehousedata


autoCompleteOff

textField
fullWidth
idRefinerybatchWarehousecity
nameRefinerybatchWarehousecity
variantStandard
labelLocationOfTheWarehouse
cityCountry
valueRefinerybatchWarehousecity
onChangeEvent
updateFieldVal
event
refineryDetails
index
warehousecity
batchTypeRefinerywarehousedata


autoCompleteOff

textField
fullWidth
idRefinerybatchLoadedQuant
nameRefinerybatchLoadedQuant
variantStandard
labelLoaded
quantityMt
valueRefinerybatchLoadedQuant
onChangeEvent
updateFieldVal
event
refineryDetails
index
loadedQuant
batchTypeRefinerywarehousedata


autoCompleteOff

div

divClassNameCustomInputWrapper
textField
fullWidth
idRefinerybatchBatchNoTwo
nameRefinerybatchBatchNoTwo
variantStandard
labelBatchNo
fromSectionCTab_1
valueRefinerybatchBatchNoTwo
onChangeEvent
updateFieldVal
event
refineryDetails
index
batchNoTwo
batchTypeRefinerywarehousedata


autoCompleteOff

p
titleRemove
className
refineryDetailsLength_2
removeRefineryRemoveNotAllowed
removeRefineryRemove

onClick
removeRow
index
refineryDetails
batchTypeRefinerywarehousedata




p
div
card



p
classNameAdd
titleAddNewBatch
onClick
addNewRow
refineryDetails
batchDetailsLength
batchTypeRefinerywarehousedata




p
div

divClassNameFormWrapper
h4D2VolumesProducedAsShippedH4
shippedVolumeDetailsMapShippedbatchIndex
return

cardClassNameEachTranciabilityWrapper
divClassNameCustomInputWrapper
textField
fullWidth
idShippedbatchEstateNamelast
nameEstateNamelast
variantStandard
labelEstateNames
valueShippedbatchEstateNamelast
onChangeEvent
updateFieldVal
event
shippedVolumeDetails
index
estateNamelast
batchTypeShippedproducedvol


autoCompleteOff


formLabel
componentLegend
classNameFormLabelPeriodLabel

periodOfProductionDdMmYy
formLabel
localizationProviderDateAdapterAdapterDayjs
datePicker
sizeLarge
labelFrom
formatDdMmYyyy
valueShippedbatchProdFrom
onChangeEvent
updateFieldVal
event
shippedVolumeDetails
index
prodFrom
batchTypeShippedproducedvol


slotProps
textField
variantStandard
errorFalse



localizationProvider

localizationProviderDateAdapterAdapterDayjs
datePicker
sizeLarge
labelTo
formatDdMmYyyy
valueShippedbatchProdTo
onChangeEvent
updateFieldVal
event
shippedVolumeDetails
index
prodTo
batchTypeShippedproducedvol


slotProps
textField
variantStandard
errorFalse



localizationProvider
div

divClassNameCustomInputWrapper
textField
fullWidth
idShippedbatchFebSupplied
nameShippedbatchFebSupplied
variantStandard
labelFfbSuppliedMt
valueShippedbatchFebSupplied
onChangeEvent
updateFieldVal
event
shippedVolumeDetails
index
febSupplied
batchTypeShippedproducedvol


autoCompleteOff

textField
fullWidth
idShippedbatchCpoProduced
nameCpoProduced
variantStandard
labelCpoProducedMt
valueShippedbatchCpoProduced
onChangeEvent
updateFieldVal
event
shippedVolumeDetails
index
cpoProduced
batchTypeShippedproducedvol


autoCompleteOff

p
titleRemove
className
shippedVolumeDetailsLength_2
removeRefineryRemoveNotAllowed
removeRefineryRemove

onClick
removeRow
index
shippedVolumeDetails
batchTypeShippedproducedvol




p
div
card



p
classNameAdd
titleAddNewBatch
onClick
addNewRow
shippedVolumeDetails
10
batchTypeShippedproducedvol




p

formControlClassNameInputWrapper
button
classNameButtonClass
colorPrimary
variantContained
fullWidth
typeSubmit
width_10px
onClickFormikHandleSubmit

submit
button
formControl
div
div
tabPanel

traceabilityGhgDetailsTabContentEnd
form
tabContext




exportDefaultDeliveryForm
